### PR TITLE
GHC 9.8.1

### PR DESCRIPTION
**Pull request by AutonomousOrganization**
+ pretty big refactor of Nostr.Db towards swapable (Database be Db)

### CODE REVIEW

**Comment by lontivero** [comment]
I cannot review Haskell code but it would help to have better commit names because they we us context. Anyway, nice project.

**Comment by AutonomousOrganization** [comment]
^ you are not wrong (I use commits like Mario save points)

@ZenenTreadwell want to confirm the relay works out here before merge? Although all DbT tests pass only refactoring . . .

**Comment by AutonomousOrganization** [comment]
I like where this is going but branch is now broken so closing

**Comment by ZenenTreadwell** [comment]
Missed the ping here - we're dropping this? Is there any more context on having a swappable db?

**Comment by AutonomousOrganization** [comment]
Yeah I aborted mission when adding the postgres dependencies the build broke (because I hadn't installed postgres, but still). I did merge in the refactor of the db code which was making me nervous because I kept getting constraint errors -> adding to Constraint type which resulted in this ugly monstrosity at the top of Nostr.Db.Fetch. But I don't think it changed anything and welcome you to confirm the relay is working on master ;p

**Comment by AutonomousOrganization** [comment]
There appears to be different Connection types. Code uses 

import Database.SQLite.Simple
import Database.Beam.Sqlite

i.e. open / runBeamSqlite

**Pull request closed without merging**
